sudo: false
language: node_js
cache:
  directories:
    - node_modules
notifications:
  email: false
node_js:
  - 'stable'
before_install:
 - npm i -g npm@^2.0.0.
brefore_script:
 - npm prune
script:
 - npm run test
after_success:
 - npm run semantic-release